### ISSUE TITLE
Create a new release to include changes from PR#7

### ISSUE THREAD

**Issue by abuiles** [astroband/ruby-xdr#8]
See https://github.com/stellar/ruby-xdr/pull/7

**Comment by charlie-wasp** [comment]
@abuiles hi 👋 Is there any estimated date of releasing v3.0.1 to RubyGems?

**Comment by abuiles** [comment]
@charlie-wasp hey! I'm waiting for rubygems access and then I'll publish it :)

**Comment by abuiles** [comment]
@charlie-wasp sorry for the delay -- I just released v3.0.1 -- thanks!
